stages = [
  { name = "example_parse", fixture = "tests/fixtures/sample_press_release.txt" },
  "my_real_stage",
  "example_label",
  { name = "example_write", out = "artifacts/pipeline_output.json" },
]
