name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip pytest jsonschema
      - name: Run tests
        run: |
          . .venv/bin/activate
          PYTHONPATH=. pytest -q
